#!/bin/sh

main () {
    install_rbenv
    install_gems
}

install_rbenv () {
    if test ! $(which rbenv)
    then
        echo "  Installing rbenv for you."
        brew install rbenv > /tmp/rbenv-install.log
    fi

    if test ! $(which ruby-build)
    then
        echo "  Installing ruby-build for you."
        brew install ruby-build > /tmp/ruby-build-install.log

        rbenv install 2.1.3
    fi
}

install_gems () {
    while read gem; do
        gem install $gem
    done < "${0%/*}/gems"

    rbenv rehash
}

main

