#!/bin/sh
#
# Set things up nicely

DOTFILES=$HOME/.config

case $(uname -s) in
    Darwin) OS=osx;;
    Linux)  OS=linux;;
esac

main () {
    bootstrap_platform
    install_packages
    link_dotfiles
}

bootstrap_platform () {
    # Run the platform specific bootstrap script
    if [ -x $DOTFILES/bootstrap-$OS ]
    then
        sh -c $DOTFILES/bootstrap-$OS
    fi
}

install_packages () {
    info 'Running dotifle installers'
    for installer in $(find . -name "install" -o -name "install-$OS")
    do
        sh -c "${installer}"
    done
}

link_dotfiles () {
    info 'Symlinking dotfiles into ~/.*'
    for src in $(find $DOTFILES -maxdepth 2 -name "*.symlink" -o -name "*.symlink-$OS")
    do
        dst="$HOME/.$(basename "${src%.*}")"
        if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
        then
            user "File already exists: $(basename "$src"), skipping"
        else
            ln -s "$src" "$dst"
            success "linked $src to $dst"
        fi
    done
}

# TODO Share this better
info () {
    printf "  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
    printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
    printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
    printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
    echo ''
    exit
}

main

