"GVim settings

"Minimalist approach
"c - console messages over a popup dialogs
"r - only show a right scroll bar
set guioptions=cr

"Easy on the eyes colorscheme
set background=dark
"colorscheme solarized

"Nice fonts
if has("win32")
    set guifont=Consolas:h10.5
elseif has("mac")
    set guifont=Monaco:h12
endif

"Turn off the blinking cursor in all modes
"set guicursor=a:blinkon0

"Large window, but don't resize on when vimrc is re-sourced
if !exists("loaded_gvimrc")
    set lines=52
    set columns=125
endif

"Hide mouse when typing
set mousehide

"Ensure system beep and visual bells remain disabled since t_vb is
"reset to it's default whenever the GUI is loaded.
set noerrorbells
set visualbell
set t_vb=

" Only want to do some things the first time sourcing gvimrc
let g:loaded_gvimrc = 1

