# Ensure XDG directories are defined
[[ -n $XDG_CONFIG_HOME ]] || export XDG_CONFIG_HOME="$HOME/.config"
[[ -n $XDG_CACHE_HOME ]] || export XDG_CACHE_HOME="$HOME/.cache"

# Ensure we search local first
export PATH=/usr/local/bin:${PATH}
# And remove any duplicate entries
typeset -U PATH

# The colors duke, the colors!
export CLICOLOR=1

# Remaining config is under XDG home
export ZDOTDIR=$XDG_CONFIG_HOME/zsh

# Android fun
export ANDROID_HOME=/usr/local/opt/android-sdk

# rbenv
export PATH=~/.rbenv/shims:${PATH}
eval "$(rbenv init -)"

