# This file _should_ be sourced by .bash_profile

test -f ~/.shrc && source ~/.shrc

export EDITOR='vim'
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'

# Mac specifics
export HOMEBREW_NO_ANALYTICS=1
