#!/usr/bin/env sh
#
# Essentially stole this from
# https://github.com/tacahilo/.dotfiles/commit/0c75dc897a307c976bc75e09bc40686e6f0533d1

PATH=/usr/local/bin:$PATH

TAPS=(
    homebrew/dupes
    homebrew/versions
    caskroom/fonts
)

FORMULAS=(
    git
    hub
    lua
    luajit
    "vim --override-system-vim --with-lua --with-luajit"
    jq
    rbenv
    ruby-build
    the_silver_searcher
    caskroom/cask/brew-cask
    imagemagick
    curl
)

CASKS=(
    alfred
    google-chrome
    iterm2-beta
    hipchat
    vagrant
    virtualbox
    spectacle
    java
    intellij-idea
    appcode
    install hockey-app
    github
    appcleaner
    league-of-legends
    spotify
    spotify-notifications
    sonos
    vlc
    kaleidoscope
    tunnelblick
    transmission
    paintbrush
    sketch
    imageoptim
)

function setup() {
    [ -x "/usr/local/bin/brew" ] || {
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    }
}

function install_brewfiles() {
    for tap in "${TAPS[@]}"; do
        brew tap $tap
    done

    for formula in "${FORMULAS[@]}"; do
        brew install $formula
    done
}

function install_caskfiles() {
    for cask in "${CASKS[@]}"; do
        brew cask install $cask
    done

    # Ensure alfred finds all the installed casks
    brew cask alfred link
}

function main() {
    setup

    brew update
    brew upgrade

    install_brewfiles
    install_caskfiles

    brew cleanup
    brew doctor
}

main

