#!/bin/sh
#
# Tap and install stuff from homebrew (or caskroom)

DIR=${0%/*}

function install_brewfiles() {
    while read tap; do
        brew tap $tap
    done < "${DIR}/taps"

    while read formula; do
        brew install $formula
    done < "${DIR}/formulas"
}

function install_caskfiles() {
    while read cask ; do
        brew cask install $cask
    done < "${DIR}/casks"

    # Ensure alfred finds all the installed casks
    brew cask alfred link
}

function main() {
    brew update
    brew upgrade

    install_brewfiles
    install_caskfiles

    brew cleanup
    brew doctor
}

main

