#!/usr/bin/env sh
#
# Essentially stole this from
# https://github.com/tacahilo/.dotfiles/commit/0c75dc897a307c976bc75e09bc40686e6f0533d1

# TODO Do I really want one big list for these?

PATH=/usr/local/bin:$PATH

TAPS=(
    homebrew/dupes
    homebrew/versions
    caskroom/fonts
)

FORMULAS=(
    git
    hub
    lua
    luajit
    "vim --override-system-vim --with-lua --with-luajit"
    jq
    rbenv
    ruby-build
    the_silver_searcher
    caskroom/cask/brew-cask
    imagemagick
    curl
    pngcrush
)

CASKS=(
    alfred
    google-chrome
    iterm2
    hipchat
    vagrant
    virtualbox
    spectacle
    java
    intellij-idea
    appcode
    hockey-app
    github
    appcleaner
    league-of-legends
    spotify
    spotify-notifications
    sonos
    vlc
    kaleidoscope
    tunnelblick
    transmission
    paintbrush
    sketch
    imageoptim
)

function install_brewfiles() {
    for tap in "${TAPS[@]}"; do
        brew tap $tap
    done

    for formula in "${FORMULAS[@]}"; do
        brew install $formula
    done
}

function install_caskfiles() {
    for cask in "${CASKS[@]}"; do
        brew cask install $cask
    done

    # Ensure alfred finds all the installed casks
    brew cask alfred link
}

function main() {
    brew update
    brew upgrade

    install_brewfiles
    install_caskfiles

    brew cleanup
    brew doctor
}

main

