#!/usr/bin/env sh
#
# Essentially stole this from
# https://github.com/tacahilo/.dotfiles/commit/0c75dc897a307c976bc75e09bc40686e6f0533d1

# TODO Do I really want one big list for these?

PATH=/usr/local/bin:$PATH

TAPS=(
    homebrew/dupes
    homebrew/versions
    caskroom/fonts
)

FORMULAS=(
    caskroom/cask/brew-cask
    curl
    git
    hub
    imagemagick
    jq
    lua
    luajit
    pngcrush
    rbenv
    ruby-build
    the_silver_searcher
    "vim --override-system-vim --with-lua --with-luajit"
)

CASKS=(
    alfred
    appcleaner
    appcode
    github
    google-chrome
    hex-fiend
    hipchat
    hockey-app
    imageoptim
    intellij-idea
    iterm2
    java
    kaleidoscope
    league-of-legends
    paintbrush
    qlstephen
    sketch
    sonos
    spectacle
    spotify
    spotify-notifications
    transmission
    tunnelblick
    vagrant
    virtualbox
    vlc
)

function install_brewfiles() {
    for tap in "${TAPS[@]}"; do
        brew tap $tap
    done

    for formula in "${FORMULAS[@]}"; do
        brew install $formula
    done
}

function install_caskfiles() {
    for cask in "${CASKS[@]}"; do
        brew cask install $cask
    done

    # Ensure alfred finds all the installed casks
    brew cask alfred link
}

function main() {
    brew update
    brew upgrade

    install_brewfiles
    install_caskfiles

    brew cleanup
    brew doctor
}

main

