#!/usr/bin/env zsh

# Install Alcatraz for Xcode plugin management. Feel better about pinging
# the github releases API to find the tarball rather than using their
# install script
# TODO Should double check that jq is already installed
RELEASES_URL=https://api.github.com/repos/supermarin/Alcatraz/releases
DOWNLOAD_URL=$(curl -fsSL $RELEASES_URL | jq --raw-output '.[0].assets[0].browser_download_url')
curl -fsSL $RELEASES_URL | jq --raw-output '.[0]'
PLUGINS_DIR="${HOME}/Library/Application Support/Developer/Shared/Xcode/Plug-ins"

mkdir -p "${PLUGINS_DIR}"
curl -L $DOWNLOAD_URL | tar xvz -C "${PLUGINS_DIR}"

# TODO Download and install my desired font
mkdir -p $HOME/Library/Developer/Xcode/UserData/FontAndColorThemes

