# shared portable settings
source ${HOME}/.shrc

# simple prompt with host and `~`-relative path
PS1="%m:%~ %# "
# no machine name
PS1="%~ %# "

# never play the beep
unsetopt BEEP

# even as a vim user, still used to the standard readline keybindings
bindkey -e

# history
# https://apple.stackexchange.com/questions/427561/macos-zsh-sessions-zsh-history-and-setopt-append-history
# https://zsh.sourceforge.io/Doc/Release/Options.html#History
# https://www.soberkoder.com/better-zsh-history/
HISTFILE=${XDG_DATA_HOME}/zsh/history
HISTSIZE=50000
SAVEHIST=50000
setopt HIST_IGNORE_ALL_DUPS  # don't record dupes in history
setopt HIST_IGNORE_SPACE # don't write space prefixed commands to the history file
setopt HIST_REDUCE_BLANKS
setopt SHARE_HISTORY # share history between sessions

# saner color switching rather than the nasty escape codes
# https://wiki.archlinux.org/index.php/zsh#Colors
autoload -U colors
colors

# bulk file renaming
# https://github.com/zsh-users/zsh/blob/master/Functions/Misc/zmv
autoload zmv
alias mmv='noglob -W zmv'

# initalize autocomplete
autoload -Uz compinit
compinit -d ${XDG_CACHE_HOME}/zsh/zcompdump-$ZSH_VERSION

# matches case insensitive for lowercase
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
# pasting with tabs doesn't perform completion
zstyle ':completion:*' insert-tab pending

